"$schema" = "https://starship.rs/config-schema.json"

format = """
[ $username$hostname$directory$git_branch$git_status ](bg:bg_gray) $jobs$status\
$line_break\
$character"""

right_format = """$cmd_duration"""

palette = "p10k_classic"

[palettes.p10k_classic]
bg_gray = "#444444"
dir_fg = "#0087af"
vcs_clean = "#5fd700"
vcs_modified = "#d7af00"
status_error = "#d70000"
duration_fg = "#a8a8a8"
host_fg = "#ff8700"

[username]
style_user = "bg:bg_gray fg:duration_fg"
style_root = "bg:bg_gray fg:status_error"
format = "[$user]($style)"
disabled = false

[hostname]
ssh_only = true
style = "bg:bg_gray fg:host_fg"
format = "[@$hostname ]($style)"

[directory]
style = "bg:bg_gray fg:dir_fg"
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "bg:bg_gray fg:vcs_clean"
format = " [$branch]($style)"

[git_status]
style = "bg:bg_gray fg:vcs_modified"
format = "([ $all_status$ahead_behind]($style))"

[cmd_duration]
style = "fg:duration_fg"
format = "[$duration ]($style)"

[jobs]
style = "fg:vcs_clean"
format = "[$symbol$number ]($style)"

[status]
style = "fg:status_error"
format = "[$symbol$status ]($style)"
disabled = false

[character]
success_symbol = "[❯](bold vcs_clean)"
error_symbol = "[❯](bold status_error)"
